{% set name = "httpcore" %}
{% set version = "0.13.0" %}
{% set sha256 = "d5602a0a9a5aa29937be6060acb2ac31461217d33e3e5e993038e51c841e0dec" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - h11 >=0.8,<0.10
    - sniffio ==1.*

test:
  imports:
    - httpcore
    - httpcore._async
    - httpcore._backends
    - httpcore._sync

about:
  home: https://github.com/encode/httpcore
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: A minimal low-level HTTP client.
  doc_url: https://www.encode.io/httpcore
  dev_url: https://github.com/encode/httpcore
